; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = 
	m5stack-atoms3

[env:bpi_leaf_s3]
platform = espressif32@^5.3.0
board = bpi_leaf_s3
upload_protocol = esptool
framework = arduino
upload_speed = 115200
monitor_speed = 115200
debug_tool = esp-prog
debug_init_break = tbreak setup

[env:esp32-s3-devkitc]
platform = espressif32@^5.3.0
board = esp32-s3-devkitc-1
framework = arduino
debug_tool = esp-prog
debug_init_break = tbreak setup
upload_port = com5

[env:Eltec-ESP32]
platform = espressif32@^5.3.0
board = heltec_wifi_kit_32
framework = arduino
monitor_speed = 115200
debug_tool = esp-prog
debug_init_break = tbreak setup

[env:m5stack-atoms3]
build_unflags = -std=gnu++11
build_flags = -std=gnu++17
	-DESP32S3
	-DCORE_DEBUG_LEVEL=5
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
platform = espressif32@^6.4.0
board = m5stack-atoms3
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
lib_ldf_mode = deep+
upload_protocol = esptool
framework = arduino
debug_tool = esp-builtin
monitor_speed = 115200
debug_init_break = break setup
upload_speed = 1500000
lib_deps = 
	enableit-platform
	enableit-app-kinetix
	enableit-app-otawifiupdater
	; enableit-app-bootloader
	; enableit-app-kinetichand
	; enableit-app-emgdemo
	; enableit-app-pressuremouse
	m5stack/M5Unified@^0.1.6
	m5stack/M5GFX@^0.1.6
	roboticsbrno/ServoESP32@^1.1.1
	workloads/SCServo@^1.0.0
	adafruit/Adafruit INA219@^1.2.3
	; spi
	; WiFiClientSecure
	; bblanchon/ArduinoJson@^6.20.0
	; thingsboard/ThingsBoard@^0.10.2
	; lennarthennigs/ESP Telnet@^2.1.2
	; esphome/ESPAsyncWebServer-esphome@^3.0.0
	; jchristensen/JC_Button@^2.1.2	
	; t-vk/ESP32 BLE Mouse@^0.3.1
	; ESP32Servo
# platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32#master

[env:xiao-esp32s3]
build_flags = !python gitVersion.py -std=gnu++17 -DCORE_DEBUG_LEVEL=2 -DESP32S3
platform = espressif32@^6.4.0
board = seeed_xiao_esp32s3
board_build.partitions = default_8MB.csv
build_unflags = -std=gnu++11
framework = arduino
upload_protocol = esptool
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps = 
	enableit-platform
	enableit-app-bootloader
	enableit-app-kinetix
	enableit-app-otawifiupdater
	enableit-app-webupdater
	roboticsbrno/ServoESP32@^1.1.1
	workloads/SCServo@^1.0.0
	adafruit/Adafruit INA219@^1.2.3	
	; spi
	; WiFiClientSecure
	; bblanchon/ArduinoJson@^6.20.0
	; thingsboard/ThingsBoard@^0.10.2
	; lennarthennigs/ESP Telnet@^2.1.2
	; esphome/ESPAsyncWebServer-esphome@^3.0.0
	; jchristensen/JC_Button@^2.1.2	
	; t-vk/ESP32 BLE Mouse@^0.3.1
	; ESP32Servo
#lib_deps = 
#	roboticsbrno/ServoESP32@^1.1.1
#	bblanchon/ArduinoJson@^7.4.2
#	https://github.com/reivaxy/XOLEDDisplay/archive/refs/tags/v1.0.tar.gz
#	thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.3.0