; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = m5stack-atoms3

[env:m5stack-atoms3]
platform = platformio/espressif32
board = m5stack-atoms3
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
upload_protocol = esptool
framework = arduino
debug_tool = esp-builtin
monitor_speed = 115200
debug_init_break = break setup
upload_speed = 1500000
build_flags =
    -DESP32S3
    -DCORE_DEBUG_LEVEL=5
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps = 
	spi
	WiFiClientSecure
	bblanchon/ArduinoJson@^6.20.0
	thingsboard/ThingsBoard@^0.10.2
	lennarthennigs/ESP Telnet@^2.1.2
	esphome/ESPAsyncWebServer-esphome@^3.0.0
	jchristensen/JC_Button@^2.1.2
	t-vk/ESP32 BLE Mouse@^0.3.1
	madhephaestus/ESP32Servo
	M5Unified=https://github.com/m5stack/M5Unified
	adafruit/Adafruit BusIO@^1.17.0
	adafruit/Adafruit INA219@^1.2.3
	workloads/SCServo@^1.0.1
#	m5stack/M5Unified@^0.1.6
#	m5stack/M5GFX@^0.1.6

